# Generated by Django 4.2.18 on 2025-02-04 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cover_url', models.URLField()),
                ('avatar_url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('joined_date', models.DateField()),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CarStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repairs_count', models.IntegerField()),
                ('car_make', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_stats', to='profiles.userprofile')),
            ],
        ),
    ]
