# Generated by Django 5.1.5 on 2025-02-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('photo', models.TextField(default='https://loremflickr.com/1280/720')),
                ('age', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('description', models.TextField()),
            ],
        ),
    ]
